Unnamed TestSuite
  ✘ it should fail when no stack #1 [0/1]
  ✘ it should fail on timeout #2 [0/0]
  ✘ it should fail on wrong plan 1 #3 [0/0]
  ✔ it should fail on wrong plan 2 #4 [1/1]
  ✔ it should fail on multiple ends #5 [0/0]
  ✔ it should fail on assertion after end #6 [0/0]
ReferenceError: SOME_UNDEFINED_VALIABLE is not defined
    at Function.<anonymous> (test/test-fail.js:26:2)
    at nextCase (test.js:271:13)
    at Function.end (test.js:332:23)
    at Function.<anonymous> (test/test-fail.js:22:9)
    at nextCase (test.js:271:13)
    at Function.end (test.js:332:23)
    at Function.<anonymous> (test/test-fail.js:19:9)
    at nextCase (test.js:271:13)
    at end (test.js:332:23)
    at Function.testCase.plan (test.js:260:36)
  ✘ it should fail on invalid test #7 [0/0]
  ✘ it should fail on invalid assertions #8 [0/7]
Error: Unable to swap "prop"
    at Mock.swap (test.js:460:45)
    at Function.<anonymous> (test/test-fail.js:50:7)
    at nextCase (test.js:271:13)
    at Function.end (test.js:332:23)
    at Function.<anonymous> (test/test-fail.js:45:3)
    at nextCase (test.js:271:13)
    at end (test.js:332:23)
    at nextCase (test.js:274:5)
    at Function.end (test.js:332:23)
    at Function.<anonymous> (test/test-fail.js:22:9)
  ✘ it should fail on read-only swap #9 [0/0]
  ✘ it should fail on fail #10 [0/0]
  ✘ it should handle an error without a stack #11 [0/0]
  ✘ it should handle an array as a stack #12 [0/0]
---
  ✘ it should handle an array as a stack #12 [0/0]
Error: 1
---
  ✘ it should handle an error without a stack #11 [0/0]
Error
---
  ✘ it should fail on fail #10 [0/0]
Error
---
  ✘ it should fail on read-only swap #9 [0/0]
Error: Unable to swap "prop"
---
  ✘ it should fail on invalid assertions #8 [0/7]
Error: Assertion:1: equal
expected: undefined
actual:   undefined
Error: Assertion:2: equal
expected: "2"
actual:   <null>{"a":Circular,"toJSON":()}
Error: Assertion:3: equal
expected: /1/m
actual:   /1/
Error: Assertion:4: equal
expected: []
actual:   arguments[testCase(value,message,actual,op,expected),false]
Error: Assertion:5: equal
expected: [/1/,B(),{"a":Circular,"toJSON":()}]
actual:   [/1/,B{},<null>{"a":Circular,"toJSON":()}]
Error: Assertion:6: 0 is truthy
Error: Assertion:7: throws
---
  ✘ it should fail on invalid test #7 [0/0]
ReferenceError: SOME_UNDEFINED_VALIABLE is not defined
---
  ✘ it should fail on wrong plan 1 #3 [0/0]
Error: planned 1 actual 0
---
  ✘ it should fail on timeout #2 [0/0]
Error: TIMEOUT: 1ms
---
  ✘ it should fail when no stack #1 [0/1]
Error: Assertion:1: equal
expected: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.."
actual:   ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","aaaaaaaaaaaaaaa..]
...
# FAIL  tests 1, 2, 3, 7, 8, 9, 10, 11, 12
1..12
# pass  3/12 [1/9]
---
  ✘ it should fail on assertion after end #6 [0/1]
Error: assertion after end
...
# FAIL  tests 6
1..12
# pass  2/12 [1/9]
---
  ✘ it should fail on wrong plan 2 #4 [1/2]
Error: assertion after end
...
# FAIL  tests 4
1..12
# pass  1/12 [1/9]
1..12
# pass  1/12 [1/9]
---
  ✘ it should fail on multiple ends #5 [0/0]
Error: ended multiple times
...
# FAIL  tests 5
1..12
# pass  0/12 [1/9]
